name: shlink_app
description: A Link Shortining Manager app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+12

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  hive: ^2.0.1
  hive_flutter: ^1.0.0
  json_annotation: ^4.0.1
  get: ^4.1.1
  #get:
  #  git:
  #    url: https://github.com/jonataslaw/getx.git
  #    ref: dev
  uuid: ^3.0.0
  #share_plus: ^2.0.0
  share: ^2.0.1

  flutter_dotenv: ^5.0.2

  receive_sharing_intent: ^1.4.2
  bottom_navy_bar: ^6.0.0
  url_launcher: ^6.0.3
  intl: ^0.17.0
  
  #flutter_map: ^0.12.0
  flutter_map: # REPLACE WITH PUBGET VERSION WHEN LATLONG2 GOES LIVE
    git:
      url: https://github.com/passsy/flutter_map.git
      ref: latlong2
  apple_maps_flutter: ^1.0.0
  google_maps_flutter: ^2.0.1

  latlong2: ^0.8.0
  cached_network_image: ^3.0.0
  
  package_info_plus: ^2.0.0

  flutter_svg: ^1.1.5
  shared_preferences: ^2.0.5

  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  
  #shlink: ^0.7.0
  shlink: 
    git:
      url: https://github.com/poster983/dart_shlink.git
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  pull_down_button: ^0.3.1
  favicon: ^1.1.0

  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  flutter_neumorphic: ^3.2.0
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  #flutter packages pub run build_runner build
  json_serializable: ^6.5.1
  flutter_launcher_icons: ^0.10.0
  drift_dev: ^2.2.0+1

  #analyzer: "0.38.2"


#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/leg_android.png"
  image_path_ios: "assets/app_icon/ios_icon.png"
  adaptive_icon_background: "assets/app_icon/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon/adaptive_icon_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - .env
    - assets/app_icon/rounded.png

  fonts: 
    - family: Ubuntu #for Logo and Titles
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
    - family: WorkSans #For general Text
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family: SFProDisplay 
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SFProRounded 
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
